using System;
using System.IO;
using Autofac;
using FluentAssertions;
using FreeBird.Core.DependencyInjection;
using FreeBird.Core.Watch;
using Serilog;

namespace FreeBird.Core.Tests.DependencyInjection;

/// <summary>
/// T16 — Verifies that the v3.4 multi-input watch infrastructure (WatchSupervisor +
/// WatchTask factory) resolves through the Autofac container after CoreModule
/// registers them. The IWatchOrchestrator nested factory (Func&lt;IWatchOrchestrator&gt;)
/// is auto-generated by Autofac when WatchTask is registered, so a successful
/// Func&lt;WatchInput, WatchTask&gt; resolution implicitly proves the nested factory
/// works.
/// </summary>
public class MultiInputWatchResolutionTests
{
    private static IContainer BuildContainer()
    {
        var builder = new ContainerBuilder();
        builder.RegisterModule<CoreModule>();
        var logger = new LoggerConfiguration().CreateLogger();
        builder.RegisterInstance<ILogger>(logger).SingleInstance();
        return builder.Build();
    }

    [Fact]
    public void CoreModule_Resolves_WatchSupervisor()
    {
        using var container = BuildContainer();
        var supervisor = container.Resolve<WatchSupervisor>();
        supervisor.Should().NotBeNull();
    }

    [Fact]
    public void CoreModule_WatchSupervisor_IsSingleInstance_AcrossScopes()
    {
        using var container = BuildContainer();
        using var scopeA = container.BeginLifetimeScope();
        using var scopeB = container.BeginLifetimeScope();

        var fromA = scopeA.Resolve<WatchSupervisor>();
        var fromB = scopeB.Resolve<WatchSupervisor>();

        fromA.Should().BeSameAs(fromB,
            because: "WatchSupervisor must be process-wide singleton — one per fb watch run");
    }

    [Fact]
    public void CoreModule_Resolves_WatchTask_FactoryAsFuncOfWatchInput()
    {
        using var container = BuildContainer();
        var factory = container.Resolve<Func<WatchInput, WatchTask>>();
        factory.Should().NotBeNull();

        var tempDir = Path.Combine(Path.GetTempPath(), $"fb-di-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        try
        {
            var input = WatchInput.FromPath(tempDir);
            var task = factory(input);
            task.Should().NotBeNull();
            task.Input.Should().BeSameAs(input);
        }
        finally
        {
            try { Directory.Delete(tempDir, recursive: true); } catch { }
        }
    }

    [Fact]
    public void CoreModule_WatchTask_FactoryProducesTransientInstances()
    {
        using var container = BuildContainer();
        var factory = container.Resolve<Func<WatchInput, WatchTask>>();

        var tempDir = Path.Combine(Path.GetTempPath(), $"fb-di-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        try
        {
            var input1 = WatchInput.FromPath(tempDir);
            var input2 = WatchInput.FromPath(tempDir);
            var t1 = factory(input1);
            var t2 = factory(input2);

            t1.Should().NotBeSameAs(t2,
                because: "WatchTask must be transient — one per WatchInput, never shared");
        }
        finally
        {
            try { Directory.Delete(tempDir, recursive: true); } catch { }
        }
    }
}
